packages:
  - packages/*
  - apps/*

catalog:
  "@tailwindcss/vite": ^4.1.13
  oxlint: ^1.16.0
  prettier: ^3.4.2
  react: ^19.1.1
  react-dom: ^19.1.1
  rxjs: ^7.8.1
  tailwindcss: ^4.1.13
  typescript: ^5.8.3
